package jetbrains.buildServer.agent

enum class TargetType(final val priority: Int) {
    NotApplicable(0),

    Tool(100), // dotnet, msbuild, nuget ...

    Host(200), // java, dotnet, mono ...

    ProfilerOfPerformance(300),// dotTrace ...
    ProfilerOfMemory(310), // dotMemory ...
    ProfilerOfCodeCoverage(320), // dotCover ...
}