package jetbrains.buildServer.agent

enum class TargetType(val priority: Int) {
    NotApplicable(0),

    Tool(100), // dotnet, msbuild, nuget ...

    Host(200), // java, dotnet, mono ...

    PerformanceProfiler(300),// dotTrace ...
    MemoryProfiler(310), // dotMemory ...
    CodeCoverageProfiler(320), // dotCover ...
}