plugins{
    id 'io.github.rodm.teamcity-common'
    id 'plugin.conventions'
}

dependencies {
    compileOnly("com.google.code.gson:gson")
    api('org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm') {
      transitive = false
    }
}

teamcity {
    version = project.teamcityVersion
    allowSnapshotVersions = true
}