package jetbrains.buildServer.nunit

import jetbrains.buildServer.tools.available.DownloadableToolVersion
import org.testng.Assert.assertEquals
import org.testng.annotations.Test
import java.io.StringReader
import kotlin.streams.toList

class ToolsParserTest {

    @Test
    fun `should parse github json`() {
        // arrange
        val parser = ToolsParserImpl()
        val expectedPackages = listOf(
            "NUnit.ConsoleRunner.4.0.1.nupkg",
            "NUnit.ConsoleRunner.4.0.0.nupkg",

            "NUnit.Console-3.19.2.zip",
            "NUnit.Console-3.19.1.zip",
            "NUnit.Console-3.19.0.zip",
            "NUnit.Console-3.18.3.zip",
            "NUnit.Console-3.18.2.zip",
            "NUnit.Console-3.18.1.zip",
            "NUnit.Console-3.18.0.zip",
            "NUnit.Console-3.17.0.zip",
            "NUnit.Console-3.15.4.zip",
            "NUnit.Console-3.15.5.zip",
            "NUnit.Console-3.16.2.zip",
            "NUnit.Console-3.16.1.zip",
            "NUnit.Console-3.16.0.zip",
            "NUnit.Console-3.15.2.zip",
            "NUnit.Console-3.15.0.zip",
            "NUnit.Console-3.14.0.zip",
            "NUnit.Console-3.13.2.zip",
            "NUnit.Console-3.13.1.zip",
            "NUnit.Console-3.13.0.zip",
            "NUnit.Console-3.12.0.zip",
            "NUnit.Console-3.11.1.zip",
            "NUnit.Console-3.11.0.zip",
            "NUnit.Console-3.10.0.zip",
            "NUnit.Console-3.9.0.zip",
            "NUnit.Console-3.8.0.zip",
            "NUnit.Console-3.7.0.zip"
        )

        // act
        val tools = parser.parse(StringReader(GithubResponseExtended))

        // assert
        assertEquals(tools.size, 28)
        assertEquals(tools.stream().map { it.destinationFileName }.toList(), expectedPackages)
    }

    @Test
    fun `should return empty list in case of error`() {
        // arrange
        val parser = ToolsParserImpl()

        // act
        val tools = parser.parse(StringReader("wrong-json"))

        // assert
        assertEquals(tools, emptyList<DownloadableToolVersion>())
    }

    companion object {
        private val GithubResponseExtended = """
            [
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/197855557",
                  "assets":[
                     {
                        "name":"nunit-console-runner.4.0.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/4.0.1/nunit-console-runner.4.0.1.nupkg"
                     },
                     {
                        "name":"NUnit.Console-4.0.1.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/4.0.1/NUnit.Console-4.0.1.zip"
                     },
                     {
                        "name":"NUnit.Console.4.0.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/4.0.1/NUnit.Console.4.0.1.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.4.0.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/4.0.1/NUnit.ConsoleRunner.4.0.1.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.4.0.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/4.0.1/NUnit.ConsoleRunner.NetCore.4.0.1.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.4.0.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/4.0.1/NUnit.Engine.4.0.1.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.4.0.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/4.0.1/NUnit.Engine.Api.4.0.1.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/197855555",
                  "assets":[
                     {
                        "name":"nunit-console-runner.4.0.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/4.0.0/nunit-console-runner.4.0.0.nupkg"
                     },
                     {
                        "name":"NUnit.Console-4.0.0.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/4.0.0/NUnit.Console-4.0.0.zip"
                     },
                     {
                        "name":"NUnit.Console.4.0.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/4.0.0/NUnit.Console.4.0.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.4.0.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/4.0.0/NUnit.ConsoleRunner.4.0.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.4.0.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/4.0.0/NUnit.ConsoleRunner.NetCore.4.0.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.4.0.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/4.0.0/NUnit.Engine.4.0.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.4.0.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/4.0.0/NUnit.Engine.Api.4.0.0.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/197874973",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.19.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.19.2/nunit-console-runner.3.19.2.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.19.2.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.19.2/NUnit.Console-3.19.2.zip"
                     },
                     {
                        "name":"NUnit.Console.3.19.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.19.2/NUnit.Console.3.19.2.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.19.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.19.2/NUnit.ConsoleRunner.3.19.2.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.19.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.19.2/NUnit.ConsoleRunner.NetCore.3.19.2.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.19.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.19.2/NUnit.Engine.3.19.2.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.19.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.19.2/NUnit.Engine.Api.3.19.2.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/195443632",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.19.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.19.1/nunit-console-runner.3.19.1.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.19.1.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.19.1/NUnit.Console-3.19.1.zip"
                     },
                     {
                        "name":"NUnit.Console.3.19.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.19.1/NUnit.Console.3.19.1.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.19.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.19.1/NUnit.ConsoleRunner.3.19.1.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.19.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.19.1/NUnit.ConsoleRunner.NetCore.3.19.1.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.19.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.19.1/NUnit.Engine.3.19.1.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.19.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.19.1/NUnit.Engine.Api.3.19.1.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/192491579",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.19.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.19.0/nunit-console-runner.3.19.0.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.19.0.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.19.0/NUnit.Console-3.19.0.zip"
                     },
                     {
                        "name":"NUnit.Console.3.19.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.19.0/NUnit.Console.3.19.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.19.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.19.0/NUnit.ConsoleRunner.3.19.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.19.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.19.0/NUnit.ConsoleRunner.NetCore.3.19.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.19.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.19.0/NUnit.Engine.3.19.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.19.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.19.0/NUnit.Engine.Api.3.19.0.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/178998993",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.18.3.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.3/nunit-console-runner.3.18.3.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.18.3.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.3/NUnit.Console-3.18.3.zip"
                     },
                     {
                        "name":"NUnit.Console.3.18.3.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.3/NUnit.Console.3.18.3.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.18.3.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.3/NUnit.ConsoleRunner.3.18.3.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.Net80.3.18.3.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.3/NUnit.ConsoleRunner.Net80.3.18.3.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.18.3.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.3/NUnit.ConsoleRunner.NetCore.3.18.3.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.18.3.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.3/NUnit.Engine.3.18.3.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.18.3.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.3/NUnit.Engine.Api.3.18.3.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/170068547",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.18.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.2/nunit-console-runner.3.18.2.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.18.2.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.2/NUnit.Console-3.18.2.zip"
                     },
                     {
                        "name":"NUnit.Console.3.18.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.2/NUnit.Console.3.18.2.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.18.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.2/NUnit.ConsoleRunner.3.18.2.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.18.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.2/NUnit.ConsoleRunner.NetCore.3.18.2.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.18.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.2/NUnit.Engine.3.18.2.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.18.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.2/NUnit.Engine.Api.3.18.2.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/165979821",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.18.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.1/nunit-console-runner.3.18.1.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.18.1.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.1/NUnit.Console-3.18.1.zip"
                     },
                     {
                        "name":"NUnit.Console.3.18.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.1/NUnit.Console.3.18.1.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.18.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.1/NUnit.ConsoleRunner.3.18.1.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.18.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.1/NUnit.ConsoleRunner.NetCore.3.18.1.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.18.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.1/NUnit.Engine.3.18.1.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.18.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.1/NUnit.Engine.Api.3.18.1.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/165763528",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.18.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.0/nunit-console-runner.3.18.0.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.18.0.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.0/NUnit.Console-3.18.0.zip"
                     },
                     {
                        "name":"NUnit.Console.3.18.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.0/NUnit.Console.3.18.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.18.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.0/NUnit.ConsoleRunner.3.18.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.18.0.snupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.0/NUnit.ConsoleRunner.3.18.0.snupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.18.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.0/NUnit.ConsoleRunner.NetCore.3.18.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.18.0.snupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.0/NUnit.ConsoleRunner.NetCore.3.18.0.snupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.18.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.0/NUnit.Engine.3.18.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.18.0.snupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.0/NUnit.Engine.3.18.0.snupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.18.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.0/NUnit.Engine.Api.3.18.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.18.0.snupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.18.0/NUnit.Engine.Api.3.18.0.snupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/138380096",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.17.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.17.0/nunit-console-runner.3.17.0.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.17.0.msi",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.17.0/NUnit.Console-3.17.0.msi"
                     },
                     {
                        "name":"NUnit.Console-3.17.0.wixpdb",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.17.0/NUnit.Console-3.17.0.wixpdb"
                     },
                     {
                        "name":"NUnit.Console-3.17.0.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.17.0/NUnit.Console-3.17.0.zip"
                     },
                     {
                        "name":"NUnit.Console.3.17.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.17.0/NUnit.Console.3.17.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.17.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.17.0/NUnit.ConsoleRunner.3.17.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.17.0.snupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.17.0/NUnit.ConsoleRunner.3.17.0.snupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.17.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.17.0/NUnit.ConsoleRunner.NetCore.3.17.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.17.0.snupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.17.0/NUnit.ConsoleRunner.NetCore.3.17.0.snupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.17.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.17.0/NUnit.Engine.3.17.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.17.0.snupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.17.0/NUnit.Engine.3.17.0.snupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.17.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.17.0/NUnit.Engine.Api.3.17.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.17.0.snupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.17.0/NUnit.Engine.Api.3.17.0.snupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/104516174",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.15.4.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.4/nunit-console-runner.3.15.4.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.15.4.msi",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.4/NUnit.Console-3.15.4.msi"
                     },
                     {
                        "name":"NUnit.Console-3.15.4.wixpdb",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.4/NUnit.Console-3.15.4.wixpdb"
                     },
                     {
                        "name":"NUnit.Console-3.15.4.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.4/NUnit.Console-3.15.4.zip"
                     },
                     {
                        "name":"NUnit.Console.3.15.4.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.4/NUnit.Console.3.15.4.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.15.4.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.4/NUnit.ConsoleRunner.3.15.4.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.15.4.snupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.4/NUnit.ConsoleRunner.3.15.4.snupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.15.4.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.4/NUnit.ConsoleRunner.NetCore.3.15.4.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.15.4.snupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.4/NUnit.ConsoleRunner.NetCore.3.15.4.snupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.15.4.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.4/NUnit.Engine.3.15.4.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.15.4.snupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.4/NUnit.Engine.3.15.4.snupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.15.4.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.4/NUnit.Engine.Api.3.15.4.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.15.4.snupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.4/NUnit.Engine.Api.3.15.4.snupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/122615079",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.15.5.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.5/nunit-console-runner.3.15.5.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.15.5.msi",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.5/NUnit.Console-3.15.5.msi"
                     },
                     {
                        "name":"NUnit.Console-3.15.5.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.5/NUnit.Console-3.15.5.zip"
                     },
                     {
                        "name":"NUnit.Console.3.15.5.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.5/NUnit.Console.3.15.5.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.15.5.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.5/NUnit.ConsoleRunner.3.15.5.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.15.5.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.5/NUnit.ConsoleRunner.NetCore.3.15.5.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.15.5.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.5/NUnit.Engine.3.15.5.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.15.5.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.5/NUnit.Engine.Api.3.15.5.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/93100559",
                  "assets":[
                     {
                        "name":"NUnit.Console.3.16.3.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.3/NUnit.Console.3.16.3.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.16.3.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.3/NUnit.ConsoleRunner.3.16.3.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.16.3.snupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.3/NUnit.ConsoleRunner.3.16.3.snupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.16.3.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.3/NUnit.ConsoleRunner.NetCore.3.16.3.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.16.3.snupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.3/NUnit.ConsoleRunner.NetCore.3.16.3.snupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/88631271",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.16.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.2/nunit-console-runner.3.16.2.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.16.2.msi",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.2/NUnit.Console-3.16.2.msi"
                     },
                     {
                        "name":"NUnit.Console-3.16.2.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.2/NUnit.Console-3.16.2.zip"
                     },
                     {
                        "name":"NUnit.Console.3.16.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.2/NUnit.Console.3.16.2.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.16.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.2/NUnit.ConsoleRunner.3.16.2.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.16.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.2/NUnit.ConsoleRunner.NetCore.3.16.2.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.16.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.2/NUnit.Engine.3.16.2.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.16.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.2/NUnit.Engine.Api.3.16.2.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/87917355",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.16.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.1/nunit-console-runner.3.16.1.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.16.1.msi",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.1/NUnit.Console-3.16.1.msi"
                     },
                     {
                        "name":"NUnit.Console-3.16.1.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.1/NUnit.Console-3.16.1.zip"
                     },
                     {
                        "name":"NUnit.Console.3.16.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.1/NUnit.Console.3.16.1.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.16.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.1/NUnit.ConsoleRunner.3.16.1.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.16.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.1/NUnit.ConsoleRunner.NetCore.3.16.1.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.16.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.1/NUnit.Engine.3.16.1.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.16.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.1/NUnit.Engine.Api.3.16.1.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/83078312",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.16.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.0/nunit-console-runner.3.16.0.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.16.0.msi",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.0/NUnit.Console-3.16.0.msi"
                     },
                     {
                        "name":"NUnit.Console-3.16.0.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.0/NUnit.Console-3.16.0.zip"
                     },
                     {
                        "name":"NUnit.Console.3.16.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.0/NUnit.Console.3.16.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.16.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.0/NUnit.ConsoleRunner.3.16.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.16.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.0/NUnit.ConsoleRunner.NetCore.3.16.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.16.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.0/NUnit.Engine.3.16.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.16.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.16.0/NUnit.Engine.Api.3.16.0.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/71006297",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.15.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.2/nunit-console-runner.3.15.2.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.15.2.msi",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.2/NUnit.Console-3.15.2.msi"
                     },
                     {
                        "name":"NUnit.Console-3.15.2.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.2/NUnit.Console-3.15.2.zip"
                     },
                     {
                        "name":"NUnit.Console.3.15.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.2/NUnit.Console.3.15.2.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.15.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.2/NUnit.ConsoleRunner.3.15.2.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.15.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.2/NUnit.ConsoleRunner.NetCore.3.15.2.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.15.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.2/NUnit.Engine.3.15.2.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.15.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.2/NUnit.Engine.Api.3.15.2.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/59271554",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.15.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.0/nunit-console-runner.3.15.0.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.15.0.msi",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.0/NUnit.Console-3.15.0.msi"
                     },
                     {
                        "name":"NUnit.Console-3.15.0.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.0/NUnit.Console-3.15.0.zip"
                     },
                     {
                        "name":"NUnit.Console.3.15.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.0/NUnit.Console.3.15.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.15.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.0/NUnit.ConsoleRunner.3.15.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.15.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.0/NUnit.ConsoleRunner.NetCore.3.15.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.15.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.0/NUnit.Engine.3.15.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.15.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.0/NUnit.Engine.Api.3.15.0.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/58851439",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.15.0-beta1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.0-beta1/nunit-console-runner.3.15.0-beta1.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.15.0-beta1.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.0-beta1/NUnit.Console-3.15.0-beta1.zip"
                     },
                     {
                        "name":"NUnit.Console-3.15.0.msi",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.0-beta1/NUnit.Console-3.15.0.msi"
                     },
                     {
                        "name":"NUnit.Console.3.15.0-beta1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.0-beta1/NUnit.Console.3.15.0-beta1.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.15.0-beta1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.0-beta1/NUnit.ConsoleRunner.3.15.0-beta1.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.15.0-beta1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.0-beta1/NUnit.ConsoleRunner.NetCore.3.15.0-beta1.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.15.0-beta1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.0-beta1/NUnit.Engine.3.15.0-beta1.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.15.0-beta1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.15.0-beta1/NUnit.Engine.Api.3.15.0-beta1.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/57202541",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.14.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.14.0/nunit-console-runner.3.14.0.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.14.0.msi",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.14.0/NUnit.Console-3.14.0.msi"
                     },
                     {
                        "name":"NUnit.Console-3.14.0.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.14.0/NUnit.Console-3.14.0.zip"
                     },
                     {
                        "name":"NUnit.Console.3.14.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.14.0/NUnit.Console.3.14.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.14.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.14.0/NUnit.ConsoleRunner.3.14.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.14.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.14.0/NUnit.ConsoleRunner.NetCore.3.14.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.14.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.14.0/NUnit.Engine.3.14.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.14.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.14.0/NUnit.Engine.Api.3.14.0.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/56504519",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.13.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13.2/nunit-console-runner.3.13.2.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.13.2.msi",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13.2/NUnit.Console-3.13.2.msi"
                     },
                     {
                        "name":"NUnit.Console-3.13.2.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13.2/NUnit.Console-3.13.2.zip"
                     },
                     {
                        "name":"NUnit.Console.3.13.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13.2/NUnit.Console.3.13.2.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.13.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13.2/NUnit.ConsoleRunner.3.13.2.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.13.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13.2/NUnit.ConsoleRunner.NetCore.3.13.2.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.13.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13.2/NUnit.Engine.3.13.2.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.13.2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13.2/NUnit.Engine.Api.3.13.2.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/56276489",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.13.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13.1/nunit-console-runner.3.13.1.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.13.1.msi",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13.1/NUnit.Console-3.13.1.msi"
                     },
                     {
                        "name":"NUnit.Console-3.13.1.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13.1/NUnit.Console-3.13.1.zip"
                     },
                     {
                        "name":"NUnit.Console.3.13.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13.1/NUnit.Console.3.13.1.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.13.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13.1/NUnit.ConsoleRunner.3.13.1.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.13.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13.1/NUnit.ConsoleRunner.NetCore.3.13.1.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.13.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13.1/NUnit.Engine.3.13.1.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.13.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13.1/NUnit.Engine.Api.3.13.1.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/54377393",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.13.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13/nunit-console-runner.3.13.0.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.13.0.msi",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13/NUnit.Console-3.13.0.msi"
                     },
                     {
                        "name":"NUnit.Console-3.13.0.wixpdb",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13/NUnit.Console-3.13.0.wixpdb"
                     },
                     {
                        "name":"NUnit.Console-3.13.0.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13/NUnit.Console-3.13.0.zip"
                     },
                     {
                        "name":"NUnit.Console.3.13.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13/NUnit.Console.3.13.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.13.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13/NUnit.ConsoleRunner.3.13.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.13.0.snupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13/NUnit.ConsoleRunner.3.13.0.snupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.13.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13/NUnit.ConsoleRunner.NetCore.3.13.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.13.0.snupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13/NUnit.ConsoleRunner.NetCore.3.13.0.snupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.13.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13/NUnit.Engine.3.13.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.13.0.snupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13/NUnit.Engine.3.13.0.snupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.13.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13/NUnit.Engine.Api.3.13.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.13.0.snupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.13/NUnit.Engine.Api.3.13.0.snupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/36521564",
                  "assets":[
                     {
                        "name":"NUnit.Console-3.12.0-beta2.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.12.0-beta2/NUnit.Console-3.12.0-beta2.zip"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.12.0-beta2.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.12.0-beta2/NUnit.ConsoleRunner.NetCore.3.12.0-beta2.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/36522015",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.12.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.12/nunit-console-runner.3.12.0.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.12.0.msi",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.12/NUnit.Console-3.12.0.msi"
                     },
                     {
                        "name":"NUnit.Console-3.12.0.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.12/NUnit.Console-3.12.0.zip"
                     },
                     {
                        "name":"NUnit.Console.3.12.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.12/NUnit.Console.3.12.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.12.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.12/NUnit.ConsoleRunner.3.12.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.12.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.12/NUnit.Engine.3.12.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.12.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.12/NUnit.Engine.Api.3.12.0.nupkg"
                     },
                     {
                        "name":"NUnit.Runners.3.12.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.12/NUnit.Runners.3.12.0.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/29194602",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.12.0-beta1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.12.0-beta1/nunit-console-runner.3.12.0-beta1.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.12.0-beta1.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.12.0-beta1/NUnit.Console-3.12.0-beta1.zip"
                     },
                     {
                        "name":"NUnit.Console.3.12.0-beta1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.12.0-beta1/NUnit.Console.3.12.0-beta1.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.12.0-beta1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.12.0-beta1/NUnit.ConsoleRunner.3.12.0-beta1.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.NetCore.3.12.0-beta1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.12.0-beta1/NUnit.ConsoleRunner.NetCore.3.12.0-beta1.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.12.0-beta1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.12.0-beta1/NUnit.Engine.3.12.0-beta1.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.12.0-beta1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.12.0-beta1/NUnit.Engine.Api.3.12.0-beta1.nupkg"
                     },
                     {
                        "name":"nunit.engine.netstandard.3.12.0-beta1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.12.0-beta1/nunit.engine.netstandard.3.12.0-beta1.nupkg"
                     },
                     {
                        "name":"NUnit.Runners.3.12.0-beta1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.12.0-beta1/NUnit.Runners.3.12.0-beta1.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/23704068",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.11.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.11.1/nunit-console-runner.3.11.1.nupkg"
                     },
                     {
                        "name":"nunit-console-with-extensions.3.11.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.11.1/nunit-console-with-extensions.3.11.1.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.11.1.msi",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.11.1/NUnit.Console-3.11.1.msi"
                     },
                     {
                        "name":"NUnit.Console-3.11.1.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.11.1/NUnit.Console-3.11.1.zip"
                     },
                     {
                        "name":"NUnit.Console.3.11.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.11.1/NUnit.Console.3.11.1.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.11.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.11.1/NUnit.ConsoleRunner.3.11.1.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.11.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.11.1/NUnit.Engine.3.11.1.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.11.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.11.1/NUnit.Engine.Api.3.11.1.nupkg"
                     },
                     {
                        "name":"nunit.engine.netstandard.3.11.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.11.1/nunit.engine.netstandard.3.11.1.nupkg"
                     },
                     {
                        "name":"NUnit.Runners.3.11.1.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.11.1/NUnit.Runners.3.11.1.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/23133846",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.11.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.11/nunit-console-runner.3.11.0.nupkg"
                     },
                     {
                        "name":"nunit-console-with-extensions.3.11.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.11/nunit-console-with-extensions.3.11.0.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.11.0.msi",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.11/NUnit.Console-3.11.0.msi"
                     },
                     {
                        "name":"NUnit.Console-3.11.0.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.11/NUnit.Console-3.11.0.zip"
                     },
                     {
                        "name":"NUnit.Console.3.11.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.11/NUnit.Console.3.11.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.11.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.11/NUnit.ConsoleRunner.3.11.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.11.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.11/NUnit.Engine.3.11.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.11.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.11/NUnit.Engine.Api.3.11.0.nupkg"
                     },
                     {
                        "name":"nunit.engine.netstandard.3.11.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.11/nunit.engine.netstandard.3.11.0.nupkg"
                     },
                     {
                        "name":"NUnit.Runners.3.11.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.11/NUnit.Runners.3.11.0.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/16312412",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.10.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.10/nunit-console-runner.3.10.0.nupkg"
                     },
                     {
                        "name":"nunit-console-with-extensions.3.10.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.10/nunit-console-with-extensions.3.10.0.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.10.0.msi",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.10/NUnit.Console-3.10.0.msi"
                     },
                     {
                        "name":"NUnit.Console-3.10.0.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.10/NUnit.Console-3.10.0.zip"
                     },
                     {
                        "name":"NUnit.Console.3.10.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.10/NUnit.Console.3.10.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.10.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.10/NUnit.ConsoleRunner.3.10.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.10.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.10/NUnit.Engine.3.10.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.10.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.10/NUnit.Engine.Api.3.10.0.nupkg"
                     },
                     {
                        "name":"nunit.engine.netstandard.3.10.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.10/nunit.engine.netstandard.3.10.0.nupkg"
                     },
                     {
                        "name":"NUnit.Runners.3.10.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.10/NUnit.Runners.3.10.0.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/12753181",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.9.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.9/nunit-console-runner.3.9.0.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.9.0.msi",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.9/NUnit.Console-3.9.0.msi"
                     },
                     {
                        "name":"NUnit.Console-3.9.0.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.9/NUnit.Console-3.9.0.zip"
                     },
                     {
                        "name":"NUnit.Console.3.9.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.9/NUnit.Console.3.9.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.9.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.9/NUnit.ConsoleRunner.3.9.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.9.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.9/NUnit.Engine.3.9.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.9.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.9/NUnit.Engine.Api.3.9.0.nupkg"
                     },
                     {
                        "name":"NUnit.Runners.3.9.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/v3.9/NUnit.Runners.3.9.0.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/9413655",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.8.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.8/nunit-console-runner.3.8.0.nupkg"
                     },
                     {
                        "name":"nunit-console-with-extensions.3.8.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.8/nunit-console-with-extensions.3.8.0.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.8.0.msi",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.8/NUnit.Console-3.8.0.msi"
                     },
                     {
                        "name":"NUnit.Console-3.8.0.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.8/NUnit.Console-3.8.0.zip"
                     },
                     {
                        "name":"NUnit.Console.3.8.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.8/NUnit.Console.3.8.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.8.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.8/NUnit.ConsoleRunner.3.8.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.8.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.8/NUnit.Engine.3.8.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.8.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.8/NUnit.Engine.Api.3.8.0.nupkg"
                     },
                     {
                        "name":"nunit.engine.netstandard.3.8.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.8/nunit.engine.netstandard.3.8.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Tool.3.8.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.8/NUnit.Engine.Tool.3.8.0.nupkg"
                     },
                     {
                        "name":"NUnit.Runners.3.8.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.8/NUnit.Runners.3.8.0.nupkg"
                     }
                  ]
               },
               {
                  "url":"https://api.github.com/repos/nunit/nunit-console/releases/7037302",
                  "assets":[
                     {
                        "name":"nunit-console-runner.3.7.0.choco.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.7/nunit-console-runner.3.7.0.choco.nupkg"
                     },
                     {
                        "name":"NUnit.Console-3.7.0.msi",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.7/NUnit.Console-3.7.0.msi"
                     },
                     {
                        "name":"NUnit.Console-3.7.0.zip",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.7/NUnit.Console-3.7.0.zip"
                     },
                     {
                        "name":"NUnit.Console.3.7.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.7/NUnit.Console.3.7.0.nupkg"
                     },
                     {
                        "name":"NUnit.ConsoleRunner.3.7.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.7/NUnit.ConsoleRunner.3.7.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.3.7.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.7/NUnit.Engine.3.7.0.nupkg"
                     },
                     {
                        "name":"NUnit.Engine.Api.3.7.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.7/NUnit.Engine.Api.3.7.0.nupkg"
                     },
                     {
                        "name":"nunit.engine.netstandard.3.7.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.7/nunit.engine.netstandard.3.7.0.nupkg"
                     },
                     {
                        "name":"NUnit.Runners.3.7.0.nupkg",
                        "browser_download_url":"https://github.com/nunit/nunit-console/releases/download/3.7/NUnit.Runners.3.7.0.nupkg"
                     }
                  ]
               }
            ]
        """.trimIndent()
    }
}